### ISSUE TITLE
Suspicious XP update based on alignment

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#235]
https://github.com/mattgodbolt/xania/blob/7a2652daf1ec09f05359ca813a605f732d75cfaf/src/fight.cpp#L1645-L1646

clang-tidy (maybe erroneously) says: "Overlapping comparisons always evaluate to true". My brain can't decode this as an issue but...

**Comment by mattgodbolt** [comment]
It probably should have been `&&` I realise now

**Comment by snellers** [comment]
@mattgodbolt  yeah it's wrong. The intent is to give a small xp bonus to neutral aggressors if the victim's alignment is sufficiently good or evil, but that's not happening. I'm fixing it by flipping the signs.

I'm also using this to make the penalties and bonuses more consistent because currently evil chars get a bigger xp bonus for slaying good, compared with good slaying evil.  And I'm also going to reduce the bonuses and penalties a too.
