### ISSUE TITLE
bug - casting spell at second identical mob works, then casting spell with no target returns nothing

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#69]
![image](https://user-images.githubusercontent.com/20328440/88864351-fe6b3e80-d1d2-11ea-8241-7a49f96b829b.png)
I was fighting two goblins and decided to cast faerie fire on the second goblin.
`c 'faerie fire' 2.gob` worked fine. (not pictured)
(pictured:) after successfully casting faerie fire on the second goblin, when I typed `c 'faerie fire'`, I just got an empty string (i.e. my prompt) in return.

**Comment by snellers** [comment]
@abraidotti  This isn't something I can repro locally now.  What I think happened is that your scenario occurred before I fixed #90 which reports if your target is already affected by faerie. And if you start a fight by attacking '2.' first, it automatically bubbles to the top of the list, so that the second cast without the number qualifier auto targeted the guy you were already fighting. Then as #90 wasn't fixed at that point, you got no message about it already affecting them.
