### ISSUE TITLE
autosac should check if I'm in the room

### ISSUE THREAD

**Issue by abraidotti** [mattgodbolt/xania#91]
![image](https://user-images.githubusercontent.com/20328440/89138675-4c04e580-d50a-11ea-93e4-36d4429c2ea3.png)
My pet killed a mob and I got a "You can't find it" when my autosac proc'd.

**Comment by snellers** [comment]
It's a side effect of a broader issue with how the death & loot sequence works. There's a related bug #72 and this ought to be fixed when that one is.

**Comment by snellers** [comment]
Fixed. This was an unintended side effect of #73.

Turns out the other issue isn't really a problem: let's say you're fighting a mob in a room, and there's already another corpse there. When it dies it will drop a corpse at the top of the item list in the room, so the autoloot/autosac commands that then get run automatically select it.
